apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-node-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.local.dev
      secretName: api-local-dev-tls
  rules:
    - host: api.local.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-node
                port:
                  number: 3000
